INSERT INTO menu (item, type, price, description, thumbnail_url) VALUES ()
INSERT INTO menu (item, type, price, description, thumbnail_url) VALUES ()
INSERT INTO menu (item, type, price, description, thumbnail_url) VALUES ()
INSERT INTO menu (item, type, price, description, thumbnail_url) VALUES ()
INSERT INTO menu (item, type, price, description, thumbnail_url) VALUES ()
INSERT INTO menu (item, type, price, description, thumbnail_url) VALUES ()
INSERT INTO menu (item, type, price, description, thumbnail_url) VALUES ()