DROP TABLE IF EXISTS menu CASCADE;
CREATE TABLE menu (
  id SERIAL PRIMARY KEY NOT NULL,
  item VARCHAR(255) NOT NULL,
  type VARCHAR(255),
  price INTEGER NOT NULL,
  description TEXT,
  thumbnail_url TEXT
);