DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  users_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  order_date DATE NOT NULL,
  total_price INTEGER NOT NULL,
  quantity INTEGER NOT NULL
);